language: node_js

node_js:
  - "8"

sudo: false

cache:
  directories:
    - node_modules

notifications:
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

install:
  - travis_retry npm install --silent

# now run the tests!
script:
  - npm test
  - npm run lint
